apiVersion: v1
kind: Pod
metadata:
  name: busy-security-user
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  containers:
    - name: sec-busy
      image: busybox
      command: ["sh", "-c", "sleep 1h"]
